
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: organization
  datasource:
    url: jdbc:mysql://localhost:3308/organization?characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: root
    password: 1
    platform: mysql
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: 192.168.1.104:7001
    #    hostname: localhost:8081
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://test:123456@192.168.1.104:8761/eureka/

server:
  address: 192.168.1.104
  port: 7001
  servlet:
    context-path: /